GET  http://localhost:8000/patients/get/all

###

GET   http://localhost:8000/

###


  


POST  http://localhost:8000/patients/register
Content-Type: application/json

{
    "id_patient": 84,
    "id_user": 5,
    "username": "Lucas",
    "email": "lucas@gmail.com",
    "password": "123445",
    "birth": "2007-06-07T03:00:00.000Z",
    "created_at": "2025-03-06T17:40:28.728Z",
    "updated_at": "2025-03-06T17:40:28.728Z",
    "profileImage": "url_.img",
    "cpf": "88888884368",
    "contact": "124762143",
    "gender": "Masculino",
    "emergencyContact": "981436932432",
    "id_address": 101,
    "street": "sla",
    "number": 20,
    "cep": "328234",
    "state": "RS",
    "city": "Sl"
}